version : '3'
services:

  app:
    build:
      context: .
      dockerfile: src/main/docker/app.dockerfile
      args:
      - BUILD_VERSION=0.1.0
    ports:
      - "8080:8080"
    links:
      - db

  db:
    image: redis:latest
